spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    stomp:
      relay:
        host: localhost
        port: 61613
    connection-timeout: 5000
    cache:
      channel.size: 100
      connection.mode: CONNECTION
    listener:
      direct:
        prefetch: 100
      simple:
        prefetch: 100
        concurrency: 5
        max-concurrency: 10

websocket:
    allowed-origins: "*"
